# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['bootstrap.py'],
    pathex=['.'],
    hiddenimports=[
        'ddgs',
        'ddgs.cli',
        'ddgs.ddgs',
        'ddgs.base',
        'ddgs.results',
        'ddgs.http_client',
        'ddgs.exceptions',
        'ddgs.utils',
        'ddgs.similarity',
        'ddgs.engines',
        'ddgs.engines.bing',
        'ddgs.engines.bing_news',
        'ddgs.engines.brave',
        'ddgs.engines.duckduckgo',
        'ddgs.engines.duckduckgo_images',
        'ddgs.engines.duckduckgo_news',
        'ddgs.engines.duckduckgo_videos',
        'ddgs.engines.google',
        'ddgs.engines.mojeek',
        'ddgs.engines.wikipedia',
        'ddgs.engines.yahoo',
        'ddgs.engines.yahoo_news',
        'ddgs.engines.yandex',
        'ddgs.engines.annasarchive',
        'ddgs.engines.grokipedia',
    ],
    binaries=[],
    datas=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ddgs',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)